export interface GcodeInfo {
  printTimeMinutes: number;
  filamentUsedMm: number;
  filamentUsedGrams: number;
  layerHeight: number;
  nozzleTemp: number;
  bedTemp: number;
  printSize: { x: number; y: number; z: number };
  slicer: string;
  filamentType: string;
}

export function parseGcode(text: string): GcodeInfo {
  const info: GcodeInfo = {
    printTimeMinutes: 0,
    filamentUsedMm: 0,
    filamentUsedGrams: 0,
    layerHeight: 0,
    nozzleTemp: 0,
    bedTemp: 0,
    printSize: { x: 0, y: 0, z: 0 },
    slicer: "",
    filamentType: "",
  };

  const lines = text.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // Cura/PrusaSlicer/Bambu Studio header comments
    if (trimmed.startsWith(";TIME:")) {
      info.printTimeMinutes = Math.round(
        parseFloat(trimmed.split(":")[1]) / 60,
      );
    }
    // PrusaSlicer/OrcaSlicer: "; estimated printing time (normal mode) = 1h 23m 45s" (also d/h/m/s combos)
    if (trimmed.toLowerCase().includes("estimated printing time")) {
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx !== -1) {
        const timePart = trimmed.slice(eqIdx + 1).trim();
        let totalSeconds = 0;
        const re = /(\d+)\s*([dhms])/gi;
        let m: RegExpExecArray | null;
        while ((m = re.exec(timePart)) !== null) {
          const val = parseInt(m[1], 10);
          const unit = m[2].toLowerCase();
          if (unit === "d") totalSeconds += val * 86400;
          else if (unit === "h") totalSeconds += val * 3600;
          else if (unit === "m") totalSeconds += val * 60;
          else if (unit === "s") totalSeconds += val;
        }
        if (totalSeconds > 0 && info.printTimeMinutes === 0) {
          info.printTimeMinutes = Math.round(totalSeconds / 60);
        }
      }
    }
    if (trimmed.startsWith(";Filament used:")) {
      // Try meters pattern first (e.g. "2.34m"), convert to mm
      const metersMatch = trimmed.match(/([\d.]+)\s*m/);
      if (metersMatch) {
        info.filamentUsedMm = parseFloat(metersMatch[1]) * 1000;
      } else {
        // Fallback to plain number (already in mm)
        const mmMatch = trimmed.match(/([\d.]+)/);
        if (mmMatch) info.filamentUsedMm = parseFloat(mmMatch[1]);
      }
    }
    if (trimmed.startsWith(";MINX:")) {
      const minX = parseFloat(trimmed.split(":")[1]);
      const maxXLine = lines.find((l) => l.trim().startsWith(";MAXX:"));
      const minYLine = lines.find((l) => l.trim().startsWith(";MINY:"));
      const maxYLine = lines.find((l) => l.trim().startsWith(";MAXY:"));
      const minZLine = lines.find((l) => l.trim().startsWith(";MINZ:"));
      const maxZLine = lines.find((l) => l.trim().startsWith(";MAXZ:"));
      if (maxXLine)
        info.printSize.x = parseFloat(maxXLine.trim().split(":")[1]) - minX;
      if (minYLine && maxYLine)
        info.printSize.y =
          parseFloat(maxYLine.trim().split(":")[1]) -
          parseFloat(minYLine.trim().split(":")[1]);
      if (minZLine && maxZLine)
        info.printSize.z =
          parseFloat(maxZLine.trim().split(":")[1]) -
          parseFloat(minZLine.trim().split(":")[1]);
    }
    if (trimmed.startsWith("; generated by")) {
      info.slicer = trimmed.replace("; generated by", "").trim();
    }
    if (trimmed.startsWith(";Slicer:")) {
      info.slicer = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Filament type:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Material:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith("; layer_height")) {
      info.layerHeight = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; initial_layer_line_height")) {
      if (!info.layerHeight)
        info.layerHeight = parseFloat(
          trimmed.split("=")[1] || trimmed.split(":")[1],
        );
    }
    if (trimmed.startsWith("; nozzle_temperature")) {
      info.nozzleTemp = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; bed_temperature")) {
      info.bedTemp = parseFloat(trimmed.split("=")[1] || trimmed.split(":")[1]);
    }

    // G-code commands
    if (trimmed.startsWith("M104") || trimmed.startsWith("M109")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.nozzleTemp)
        info.nozzleTemp = parseInt(tempMatch[1]);
    }
    if (trimmed.startsWith("M140") || trimmed.startsWith("M190")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.bedTemp) info.bedTemp = parseInt(tempMatch[1]);
    }

    // E movements for filament calculation
    if (trimmed.startsWith("G1") || trimmed.startsWith("G0")) {
      const eMatch = trimmed.match(/E([\d.]+)/);
      if (eMatch) {
        const e = parseFloat(eMatch[1]);
        if (e > info.filamentUsedMm) info.filamentUsedMm = e;
      }
    }
  }

  // Estimate filament weight from length (assuming 1.75mm filament)
  // Volume = π * r² * length, weight = volume * density (PLA ~1.24 g/cm³)
  if (info.filamentUsedMm > 0) {
    const radiusMm = 1.75 / 2;
    const volumeCm3 =
      Math.PI * Math.pow(radiusMm / 10, 2) * (info.filamentUsedMm / 10);
    info.filamentUsedGrams = volumeCm3 * 1.24;
  }

  return info;
}
