import {
  DEFAULT_FILAMENT_DIAMETER_MM,
  DEFAULT_MAX_CHARS,
  filamentWeightGrams,
  firstHeaderMinutes,
  parseTimeHeaderSeconds,
  parseGcodeTotals,
} from "./gcodeTotals";
import {
  resolveFilamentDensity,
  type FilamentFamily,
} from "./filamentProfiles";

export interface GcodeInfo {
  printTimeMinutes: number;
  filamentUsedMm: number;
  filamentUsedGrams: number;
  layerHeight: number;
  nozzleTemp: number;
  bedTemp: number;
  printSize: { x: number; y: number; z: number };
  slicer: string;
  filamentType: string;
}

export interface ParseGcodeOptions {
  /** Filament diameter in mm (default 1.75, single-sourced from gcodeTotals). */
  filamentDiameterMm?: number;
  /** Density in g/cm³ — explicit value wins over the family table. */
  densityGcm3?: number;
  /** Material family for density lookup (default PLA). */
  filamentFamily?: FilamentFamily | string;
}

/**
 * Parse the supported filament total formats without accepting partial or
 * non-finite values. Plain numbers are millimetres; an `m` suffix is metres.
 */
function parseFilamentHeaderMm(trimmed: string): number | undefined {
  const match = trimmed.match(
    /^;Filament used:\s*([+]?((?:\d+(?:\.\d*)?)|(?:\.\d+)))\s*(mm|m)?\s*$/i,
  );
  if (!match) return undefined;

  const value = Number(match[1]);
  const unit = match[3]?.toLowerCase();
  const millimetres = unit === "m" ? value * 1000 : value;
  if (
    !Number.isFinite(millimetres) ||
    millimetres < 0 ||
    millimetres > DEFAULT_MAX_CHARS
  ) {
    return undefined;
  }
  return millimetres;
}

export function parseGcode(text: string, options: ParseGcodeOptions = {}): GcodeInfo {
  const info: GcodeInfo = {
    printTimeMinutes: 0,
    filamentUsedMm: 0,
    filamentUsedGrams: 0,
    layerHeight: 0,
    nozzleTemp: 0,
    bedTemp: 0,
    printSize: { x: 0, y: 0, z: 0 },
    slicer: "",
    filamentType: "",
  };

  const lines = text.split("\n");

  // First-header-wins time: shared policy with parseGcodeTotals (T1/T2).
  // `undefined` = no header seen yet; the finished info exposes 0 when absent.
  let headerMinutes: number | undefined;
  let filamentHeaderMm: number | undefined;

  for (const line of lines) {
    const trimmed = line.trim();

    // Slicer header time via the shared reader (Cura/Prusa/Orca — see
    // parseTimeHeaderSeconds; first header wins, matching parseGcodeTotals).
    const headerSeconds = parseTimeHeaderSeconds(trimmed);
    headerMinutes = firstHeaderMinutes(headerMinutes, headerSeconds);
    if (headerMinutes !== undefined) info.printTimeMinutes = headerMinutes;
    const parsedFilamentHeaderMm = parseFilamentHeaderMm(trimmed);
    if (parsedFilamentHeaderMm !== undefined) {
      // A valid header is authoritative. Preserve the established last-valid
      // header precedence while preventing moves from replacing its value.
      filamentHeaderMm = parsedFilamentHeaderMm;
      info.filamentUsedMm = parsedFilamentHeaderMm;
    }
    if (trimmed.startsWith(";MINX:")) {
      const minX = parseFloat(trimmed.split(":")[1]);
      const maxXLine = lines.find((l) => l.trim().startsWith(";MAXX:"));
      const minYLine = lines.find((l) => l.trim().startsWith(";MINY:"));
      const maxYLine = lines.find((l) => l.trim().startsWith(";MAXY:"));
      const minZLine = lines.find((l) => l.trim().startsWith(";MINZ:"));
      const maxZLine = lines.find((l) => l.trim().startsWith(";MAXZ:"));
      if (maxXLine)
        info.printSize.x = parseFloat(maxXLine.trim().split(":")[1]) - minX;
      if (minYLine && maxYLine)
        info.printSize.y =
          parseFloat(maxYLine.trim().split(":")[1]) -
          parseFloat(minYLine.trim().split(":")[1]);
      if (minZLine && maxZLine)
        info.printSize.z =
          parseFloat(maxZLine.trim().split(":")[1]) -
          parseFloat(minZLine.trim().split(":")[1]);
    }
    if (trimmed.startsWith("; generated by")) {
      info.slicer = trimmed.replace("; generated by", "").trim();
    }
    if (trimmed.startsWith(";Slicer:")) {
      info.slicer = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Filament type:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Material:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith("; layer_height")) {
      info.layerHeight = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; initial_layer_line_height")) {
      if (!info.layerHeight)
        info.layerHeight = parseFloat(
          trimmed.split("=")[1] || trimmed.split(":")[1],
        );
    }
    if (trimmed.startsWith("; nozzle_temperature")) {
      info.nozzleTemp = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; bed_temperature")) {
      info.bedTemp = parseFloat(trimmed.split("=")[1] || trimmed.split(":")[1]);
    }

    // G-code commands
    if (trimmed.startsWith("M104") || trimmed.startsWith("M109")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.nozzleTemp)
        info.nozzleTemp = parseInt(tempMatch[1]);
    }
    if (trimmed.startsWith("M140") || trimmed.startsWith("M190")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.bedTemp) info.bedTemp = parseInt(tempMatch[1]);
    }

    // E movements for filament calculation
    if (trimmed.startsWith("G1") || trimmed.startsWith("G0")) {
      const eMatch = trimmed.match(/E([\d.]+)/);
      if (eMatch) {
        const e = parseFloat(eMatch[1]);
        if (filamentHeaderMm === undefined && e > info.filamentUsedMm) {
          info.filamentUsedMm = e;
        }
      }
    }
  }

  // A G-code header is the slicer's authoritative total when present. Without
  // one, use the stateful totals reader so absolute E resets, relative E and
  // retractions are handled instead of taking the largest raw E value.
  if (filamentHeaderMm === undefined) {
    const totals = parseGcodeTotals(text, {
      filamentDiameterMm: options.filamentDiameterMm,
      densityGcm3: resolveFilamentDensity(
        options.filamentFamily,
        options.densityGcm3,
      ),
    });
    info.filamentUsedMm = totals.extrudedMm;
  }

  // Estimate filament weight from length via the parameterized profile (W1):
  // diameter defaults to DEFAULT_FILAMENT_DIAMETER_MM, density resolves from
  // the family table (filamentProfiles) with an explicit override winning.
  // NOTE (T3): this legacy path tracks max-E (largest absolute E seen), while
  // parseGcodeTotals sums signed deltas with M82/M83 + G92 resets — the two
  // can diverge on retraction-heavy or relative-extrusion files (no behavior
  // change here; see docs/estimators-model.md §10).
  if (info.filamentUsedMm > 0) {
    const diameterMm =
      options.filamentDiameterMm ?? DEFAULT_FILAMENT_DIAMETER_MM;
    const density = resolveFilamentDensity(
      options.filamentFamily,
      options.densityGcm3,
    );
    info.filamentUsedGrams = filamentWeightGrams(
      info.filamentUsedMm,
      diameterMm,
      density,
    );
  }

  return info;
}
