import {
  DEFAULT_FILAMENT_DIAMETER_MM,
  filamentWeightGrams,
  firstHeaderMinutes,
  parseTimeHeaderSeconds,
} from "./gcodeTotals";
import {
  resolveFilamentDensity,
  type FilamentFamily,
} from "./filamentProfiles";

export interface GcodeInfo {
  printTimeMinutes: number;
  filamentUsedMm: number;
  filamentUsedGrams: number;
  layerHeight: number;
  nozzleTemp: number;
  bedTemp: number;
  printSize: { x: number; y: number; z: number };
  slicer: string;
  filamentType: string;
}

export interface ParseGcodeOptions {
  /** Filament diameter in mm (default 1.75, single-sourced from gcodeTotals). */
  filamentDiameterMm?: number;
  /** Density in g/cm³ — explicit value wins over the family table. */
  densityGcm3?: number;
  /** Material family for density lookup (default PLA). */
  filamentFamily?: FilamentFamily | string;
}

export function parseGcode(text: string, options: ParseGcodeOptions = {}): GcodeInfo {
  const info: GcodeInfo = {
    printTimeMinutes: 0,
    filamentUsedMm: 0,
    filamentUsedGrams: 0,
    layerHeight: 0,
    nozzleTemp: 0,
    bedTemp: 0,
    printSize: { x: 0, y: 0, z: 0 },
    slicer: "",
    filamentType: "",
  };

  const lines = text.split("\n");

  // First-header-wins time: shared policy with parseGcodeTotals (T1/T2).
  // `undefined` = no header seen yet; the finished info exposes 0 when absent.
  let headerMinutes: number | undefined;

  for (const line of lines) {
    const trimmed = line.trim();

    // Slicer header time via the shared reader (Cura/Prusa/Orca — see
    // parseTimeHeaderSeconds; first header wins, matching parseGcodeTotals).
    const headerSeconds = parseTimeHeaderSeconds(trimmed);
    headerMinutes = firstHeaderMinutes(headerMinutes, headerSeconds);
    if (headerMinutes !== undefined) info.printTimeMinutes = headerMinutes;
    if (trimmed.startsWith(";Filament used:")) {
      // Try meters pattern first (e.g. "2.34m"), convert to mm
      const metersMatch = trimmed.match(/([\d.]+)\s*m/);
      if (metersMatch) {
        info.filamentUsedMm = parseFloat(metersMatch[1]) * 1000;
      } else {
        // Fallback to plain number (already in mm)
        const mmMatch = trimmed.match(/([\d.]+)/);
        if (mmMatch) info.filamentUsedMm = parseFloat(mmMatch[1]);
      }
    }
    if (trimmed.startsWith(";MINX:")) {
      const minX = parseFloat(trimmed.split(":")[1]);
      const maxXLine = lines.find((l) => l.trim().startsWith(";MAXX:"));
      const minYLine = lines.find((l) => l.trim().startsWith(";MINY:"));
      const maxYLine = lines.find((l) => l.trim().startsWith(";MAXY:"));
      const minZLine = lines.find((l) => l.trim().startsWith(";MINZ:"));
      const maxZLine = lines.find((l) => l.trim().startsWith(";MAXZ:"));
      if (maxXLine)
        info.printSize.x = parseFloat(maxXLine.trim().split(":")[1]) - minX;
      if (minYLine && maxYLine)
        info.printSize.y =
          parseFloat(maxYLine.trim().split(":")[1]) -
          parseFloat(minYLine.trim().split(":")[1]);
      if (minZLine && maxZLine)
        info.printSize.z =
          parseFloat(maxZLine.trim().split(":")[1]) -
          parseFloat(minZLine.trim().split(":")[1]);
    }
    if (trimmed.startsWith("; generated by")) {
      info.slicer = trimmed.replace("; generated by", "").trim();
    }
    if (trimmed.startsWith(";Slicer:")) {
      info.slicer = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Filament type:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith(";Material:")) {
      info.filamentType = trimmed.split(":")[1].trim();
    }
    if (trimmed.startsWith("; layer_height")) {
      info.layerHeight = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; initial_layer_line_height")) {
      if (!info.layerHeight)
        info.layerHeight = parseFloat(
          trimmed.split("=")[1] || trimmed.split(":")[1],
        );
    }
    if (trimmed.startsWith("; nozzle_temperature")) {
      info.nozzleTemp = parseFloat(
        trimmed.split("=")[1] || trimmed.split(":")[1],
      );
    }
    if (trimmed.startsWith("; bed_temperature")) {
      info.bedTemp = parseFloat(trimmed.split("=")[1] || trimmed.split(":")[1]);
    }

    // G-code commands
    if (trimmed.startsWith("M104") || trimmed.startsWith("M109")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.nozzleTemp)
        info.nozzleTemp = parseInt(tempMatch[1]);
    }
    if (trimmed.startsWith("M140") || trimmed.startsWith("M190")) {
      const tempMatch = trimmed.match(/S(\d+)/);
      if (tempMatch && !info.bedTemp) info.bedTemp = parseInt(tempMatch[1]);
    }

    // E movements for filament calculation
    if (trimmed.startsWith("G1") || trimmed.startsWith("G0")) {
      const eMatch = trimmed.match(/E([\d.]+)/);
      if (eMatch) {
        const e = parseFloat(eMatch[1]);
        if (e > info.filamentUsedMm) info.filamentUsedMm = e;
      }
    }
  }

  // Estimate filament weight from length via the parameterized profile (W1):
  // diameter defaults to DEFAULT_FILAMENT_DIAMETER_MM, density resolves from
  // the family table (filamentProfiles) with an explicit override winning.
  // NOTE (T3): this legacy path tracks max-E (largest absolute E seen), while
  // parseGcodeTotals sums signed deltas with M82/M83 + G92 resets — the two
  // can diverge on retraction-heavy or relative-extrusion files (no behavior
  // change here; see docs/estimators-model.md §10).
  if (info.filamentUsedMm > 0) {
    const diameterMm =
      options.filamentDiameterMm ?? DEFAULT_FILAMENT_DIAMETER_MM;
    const density = resolveFilamentDensity(
      options.filamentFamily,
      options.densityGcm3,
    );
    info.filamentUsedGrams = filamentWeightGrams(
      info.filamentUsedMm,
      diameterMm,
      density,
    );
  }

  return info;
}
