import type { PrinterProfile } from '@/shared/types'

export type { PrinterProfile }

// Technical fields (technology / buildVolumeMm / nozzleDiameterMm / maxSpeedMmS)
// are adapted from the swordlab/open-3d-printer-database (CC-BY-4.0) — see
// docs/CREDITS.md. Economic data (value, power, usefulLife, maintenancePerHour)
// is the app's own and was NOT modified by the enrichment script.

export const printers: PrinterProfile[] = [
  {
    id: 'bambu_a1_mini',
    name: "A1 Mini",
    brand: "Bambu Lab",
    power: 170,
    value: 2000,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/brands/bambu-lab/bambu-lab-a1-mini-card-300.png",
    maxFilaments: 4,
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 180, y: 180, z: 180 },
    websiteUrl: "https://bambulab.com",
  },
  {
    id: 'bambu_a1',
    name: "A1",
    brand: "Bambu Lab",
    power: 220,
    value: 3000,
    usefulLife: 3000,
    maintenancePerHour: 0.3,
    image: "/images/printers/brands/bambu-lab/bambu-lab-a1-card-300.png",
    maxFilaments: 4,
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 256, y: 256, z: 256 },
    websiteUrl: "https://bambulab.com",
  },
  {
    id: 'bambu_p1s',
    name: "P1S",
    brand: "Bambu Lab",
    power: 350,
    value: 5500,
    usefulLife: 4000,
    maintenancePerHour: 0.4,
    image: "/images/printers/brands/bambu-lab/bambu-lab-p1s-card-300.png",
    maxFilaments: 4,
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 256, y: 256, z: 256 },
    websiteUrl: "https://bambulab.com",
  },
  {
    id: 'bambu_x1c',
    name: "X1 Carbon",
    brand: "Bambu Lab",
    power: 350,
    value: 10000,
    usefulLife: 5000,
    maintenancePerHour: 0.6,
    image: "/images/printers/brands/bambu-lab/bambu-lab-x1-carbon-card-300.png",
    maxFilaments: 4,
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 256, y: 256, z: 256 },
    websiteUrl: "https://bambulab.com",
  },
  {
    id: 'bambu_x1e',
    name: "X1E",
    brand: "Bambu Lab",
    power: 350,
    value: 13000,
    usefulLife: 5000,
    maintenancePerHour: 0.65,
    image: "/images/printers/fallback-fdm.svg",
    maxFilaments: 4,
    technology: "fdm",
    websiteUrl: "https://bambulab.com",
  },
  {
    id: 'creality_ender_3_s1',
    name: "Ender 3 S1",
    brand: "Creality",
    power: 120,
    value: 1500,
    usefulLife: 2000,
    maintenancePerHour: 0.15,
    image: "/images/printers/brands/creality/creality-ender-3-s1-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_ender_3_s1_plus',
    name: "Ender 3 S1 Plus",
    brand: "Creality",
    power: 150,
    value: 2000,
    usefulLife: 2200,
    maintenancePerHour: 0.18,
    image: "/images/printers/brands/creality/creality-ender-3-s1-plus-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_ender_3_s1_pro',
    name: "Ender 3 S1 Pro",
    brand: "Creality",
    power: 120,
    value: 1800,
    usefulLife: 2000,
    maintenancePerHour: 0.16,
    image: "/images/printers/brands/creality/creality-ender-3-s1-pro-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_ender_3_v3_se',
    name: "Ender 3 V3 SE",
    brand: "Creality",
    power: 180,
    value: 1400,
    usefulLife: 2500,
    maintenancePerHour: 0.14,
    image: "/images/printers/brands/creality/creality-ender-3-v3-se-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_ender_3_v3',
    name: "Ender 3 V3",
    brand: "Creality",
    power: 240,
    value: 2500,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_ender_3_v3_ke',
    name: "Ender 3 V3 KE",
    brand: "Creality",
    power: 240,
    value: 2300,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 226.5, y: 226.5, z: 226.5 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k1',
    name: "K1",
    brand: "Creality",
    power: 350,
    value: 3800,
    usefulLife: 3500,
    maintenancePerHour: 0.35,
    image: "/images/printers/brands/creality/creality-k1-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k1c',
    name: "K1C",
    brand: "Creality",
    power: 350,
    value: 4200,
    usefulLife: 3500,
    maintenancePerHour: 0.35,
    image: "/images/printers/brands/creality/creality-k1c-card-300.png",
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k1_se',
    name: "K1 SE",
    brand: "Creality",
    power: 350,
    value: 3500,
    usefulLife: 3500,
    maintenancePerHour: 0.3,
    image: "/images/printers/brands/creality/creality-k1-se-card-300.png",
    technology: "fdm",
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k1_max',
    name: "K1 Max",
    brand: "Creality",
    power: 400,
    value: 6000,
    usefulLife: 4000,
    maintenancePerHour: 0.45,
    image: "/images/printers/brands/creality/creality-k1-max-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 300, y: 300, z: 300 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k2',
    name: "K2",
    brand: "Creality",
    power: 500,
    value: 8000,
    usefulLife: 5000,
    maintenancePerHour: 0.5,
    image: "/images/printers/brands/creality/creality-k2-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 260, y: 260, z: 260 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k2_plus',
    name: "K2 Plus",
    brand: "Creality",
    power: 550,
    value: 10000,
    usefulLife: 5000,
    maintenancePerHour: 0.55,
    image: "/images/printers/brands/creality/creality-k2-plus-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 350, y: 350, z: 350 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_k2_pro',
    name: "K2 Pro",
    brand: "Creality",
    power: 500,
    value: 9000,
    usefulLife: 5000,
    maintenancePerHour: 0.5,
    image: "/images/printers/brands/creality/creality-k2-pro-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 300, y: 300, z: 300 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_cr10_v3',
    name: "CR-10 V3",
    brand: "Creality",
    power: 180,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 330.2, y: 330.2, z: 330.2 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_cr10_smart',
    name: "CR-10 Smart",
    brand: "Creality",
    power: 220,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 330.2, y: 330.2, z: 330.2 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_cr6_se',
    name: "CR-6 SE",
    brand: "Creality",
    power: 140,
    value: 1800,
    usefulLife: 2000,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'creality_halot_sky',
    name: "Halot Sky",
    brand: "Creality",
    power: 200,
    value: 4500,
    usefulLife: 3000,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 192, y: 120, z: 250 },
    websiteUrl: "https://www.creality.com",
  },
  {
    id: 'anycubic_kobra_2',
    name: "Kobra 2",
    brand: "Anycubic",
    power: 200,
    value: 1800,
    usefulLife: 2500,
    maintenancePerHour: 0.18,
    image: "/images/printers/brands/anycubic/anycubic-kobra-2-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_2_pro',
    name: "Kobra 2 Pro",
    brand: "Anycubic",
    power: 250,
    value: 2300,
    usefulLife: 2800,
    maintenancePerHour: 0.22,
    image: "/images/printers/brands/anycubic/anycubic-kobra-2-pro-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_2_max',
    name: "Kobra 2 Max",
    brand: "Anycubic",
    power: 280,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.28,
    image: "/images/printers/brands/anycubic/anycubic-kobra-2-max-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 445.1, y: 445.1, z: 445.1 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_3',
    name: "Kobra 3",
    brand: "Anycubic",
    power: 300,
    value: 3000,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/brands/anycubic/anycubic-kobra-3-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 253.3, y: 253.3, z: 253.3 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_3_v2',
    name: "Kobra 3 V2",
    brand: "Anycubic",
    power: 300,
    value: 3500,
    usefulLife: 3200,
    maintenancePerHour: 0.28,
    image: "/images/printers/brands/anycubic/anycubic-kobra-3-v2-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 253.3, y: 253.3, z: 253.3 },
    nozzleDiameterMm: 0.4,
    maxSpeedMmS: 600,
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_3_max',
    name: "Kobra 3 Max",
    brand: "Anycubic",
    power: 350,
    value: 5000,
    usefulLife: 3500,
    maintenancePerHour: 0.35,
    image: "/images/printers/brands/anycubic/anycubic-kobra-3-max-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 445.1, y: 445.1, z: 445.1 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_s1',
    name: "Kobra S1",
    brand: "Anycubic",
    power: 280,
    value: 2500,
    usefulLife: 3000,
    maintenancePerHour: 0.22,
    image: "/images/printers/brands/anycubic/anycubic-kobra-s1-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 250, y: 250, z: 250 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_s1_combo',
    name: "Kobra S1 Combo",
    brand: "Anycubic",
    power: 300,
    value: 3500,
    usefulLife: 3200,
    maintenancePerHour: 0.28,
    image: "/images/printers/brands/anycubic/anycubic-kobra-s1-combo-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 250, y: 250, z: 250 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_kobra_s1_max_combo',
    name: "Kobra S1 Max Combo",
    brand: "Anycubic",
    power: 350,
    value: 5500,
    usefulLife: 3500,
    maintenancePerHour: 0.35,
    image: "/images/printers/brands/anycubic/anycubic-kobra-s1-max-combo-card-300.png",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 250, y: 250, z: 250 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_mega_x',
    name: "Mega X",
    brand: "Anycubic",
    power: 180,
    value: 1500,
    usefulLife: 2000,
    maintenancePerHour: 0.15,
    image: "/images/printers/brands/anycubic/anycubic-mega-x-card-300.png",
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_vyper',
    name: "Vyper",
    brand: "Anycubic",
    power: 200,
    value: 1800,
    usefulLife: 2200,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_chiron',
    name: "Chiron",
    brand: "Anycubic",
    power: 250,
    value: 2800,
    usefulLife: 2500,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_photon_m3',
    name: "Photon M3",
    brand: "Anycubic",
    power: 120,
    value: 2000,
    usefulLife: 2000,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 163.8, y: 102.4, z: 180 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_photon_m3s',
    name: "Photon M3 Plus",
    brand: "Anycubic",
    power: 150,
    value: 3500,
    usefulLife: 2500,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 198.2, y: 123.8, z: 245 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'anycubic_photon_ultra',
    name: "Photon Ultra",
    brand: "Anycubic",
    power: 100,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 102.4, y: 57.6, z: 165 },
    websiteUrl: "https://www.anycubic.com",
  },
  {
    id: 'prusa_mk3s',
    name: "MK3S+",
    brand: "Prusa",
    power: 160,
    value: 5500,
    usefulLife: 4000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 226, y: 226, z: 226 },
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_mk4',
    name: "MK4",
    brand: "Prusa",
    power: 180,
    value: 7500,
    usefulLife: 4500,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_mk4s',
    name: "MK4S",
    brand: "Prusa",
    power: 180,
    value: 8000,
    usefulLife: 4500,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 226, y: 226, z: 226 },
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_xl_2',
    name: "XL 2-Head",
    brand: "Prusa",
    power: 350,
    value: 20000,
    usefulLife: 6000,
    maintenancePerHour: 0.6,
    image: "/images/printers/fallback-fdm.svg",
    maxFilaments: 2,
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_xl_5',
    name: "XL 5-Head",
    brand: "Prusa",
    power: 500,
    value: 35000,
    usefulLife: 6000,
    maintenancePerHour: 0.8,
    image: "/images/printers/fallback-fdm.svg",
    maxFilaments: 5,
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_mini',
    name: "Mini+",
    brand: "Prusa",
    power: 120,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 180, y: 180, z: 180 },
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'prusa_sl1s',
    name: "SL1S Speed",
    brand: "Prusa",
    power: 100,
    value: 15000,
    usefulLife: 3000,
    maintenancePerHour: 0.4,
    image: "/images/printers/fallback-resin.svg",
    websiteUrl: "https://www.prusa3d.com",
  },
  {
    id: 'elegoo_neptune_3',
    name: "Neptune 3",
    brand: "Elegoo",
    power: 180,
    value: 1200,
    usefulLife: 2000,
    maintenancePerHour: 0.12,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 238.4, y: 238.4, z: 238.4 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_neptune_3_pro',
    name: "Neptune 3 Pro",
    brand: "Elegoo",
    power: 200,
    value: 1600,
    usefulLife: 2500,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 242, y: 242, z: 242 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_neptune_3_plus',
    name: "Neptune 3 Plus",
    brand: "Elegoo",
    power: 240,
    value: 2200,
    usefulLife: 2800,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_neptune_4',
    name: "Neptune 4",
    brand: "Elegoo",
    power: 300,
    value: 2000,
    usefulLife: 3000,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 237.6, y: 237.6, z: 237.6 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_neptune_4_pro',
    name: "Neptune 4 Pro",
    brand: "Elegoo",
    power: 320,
    value: 2500,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 237.6, y: 237.6, z: 237.6 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_neptune_4_max',
    name: "Neptune 4 Max",
    brand: "Elegoo",
    power: 400,
    value: 3800,
    usefulLife: 3500,
    maintenancePerHour: 0.28,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 439.1, y: 439.1, z: 439.1 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_saturn_2',
    name: "Saturn 2",
    brand: "Elegoo",
    power: 130,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 218.9, y: 123.1, z: 250 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_saturn_3',
    name: "Saturn 3",
    brand: "Elegoo",
    power: 150,
    value: 3500,
    usefulLife: 2800,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 218.9, y: 122.9, z: 250 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_saturn_4',
    name: "Saturn 4",
    brand: "Elegoo",
    power: 180,
    value: 4500,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 218.9, y: 122.9, z: 220 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_mars_4',
    name: "Mars 4",
    brand: "Elegoo",
    power: 80,
    value: 1800,
    usefulLife: 2000,
    maintenancePerHour: 0.12,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 153.4, y: 77.8, z: 175 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_mars_5',
    name: "Mars 5",
    brand: "Elegoo",
    power: 90,
    value: 2200,
    usefulLife: 2200,
    maintenancePerHour: 0.14,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 143.4, y: 89.6, z: 150 },
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'elegoo_orangestorm_g2',
    name: "OrangeStorm G2",
    brand: "Elegoo",
    power: 500,
    value: 8000,
    usefulLife: 4000,
    maintenancePerHour: 0.5,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.elegoo.com",
  },
  {
    id: 'flashforge_guider_3',
    name: "Guider 3",
    brand: "Flashforge",
    power: 350,
    value: 8000,
    usefulLife: 4000,
    maintenancePerHour: 0.35,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'flashforge_guider_3s',
    name: "Guider 3S",
    brand: "Flashforge",
    power: 400,
    value: 10000,
    usefulLife: 4500,
    maintenancePerHour: 0.4,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'flashforge_adventurer_4',
    name: "Adventurer 4",
    brand: "Flashforge",
    power: 250,
    value: 4000,
    usefulLife: 3000,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'flashforge_adventurer_5m',
    name: "Adventurer 5M",
    brand: "Flashforge",
    power: 300,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 220, y: 220, z: 220 },
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'flashforge_finder_3',
    name: "Finder 3",
    brand: "Flashforge",
    power: 150,
    value: 2000,
    usefulLife: 2000,
    maintenancePerHour: 0.14,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'flashforge_creator_4s',
    name: "Creator 4S",
    brand: "Flashforge",
    power: 500,
    value: 25000,
    usefulLife: 5000,
    maintenancePerHour: 0.7,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 412.1, y: 412.1, z: 412.1 },
    websiteUrl: "https://www.flashforge.com",
  },
  {
    id: 'ultimaker_s3',
    name: "S3",
    brand: "UltiMaker",
    power: 250,
    value: 18000,
    usefulLife: 5000,
    maintenancePerHour: 0.5,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://ultimaker.com",
  },
  {
    id: 'ultimaker_s5',
    name: "S5",
    brand: "UltiMaker",
    power: 350,
    value: 28000,
    usefulLife: 6000,
    maintenancePerHour: 0.7,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://ultimaker.com",
  },
  {
    id: 'ultimaker_fact_4',
    name: "Factor 4",
    brand: "UltiMaker",
    power: 400,
    value: 35000,
    usefulLife: 6000,
    maintenancePerHour: 0.8,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://ultimaker.com",
  },
  {
    id: 'ultimaker_method_x',
    name: "Method X",
    brand: "UltiMaker",
    power: 300,
    value: 22000,
    usefulLife: 5000,
    maintenancePerHour: 0.6,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://ultimaker.com",
  },
  {
    id: 'ultimaker_method_xl',
    name: "Method XL",
    brand: "UltiMaker",
    power: 400,
    value: 30000,
    usefulLife: 6000,
    maintenancePerHour: 0.75,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://ultimaker.com",
  },
  {
    id: 'artillery_sidewinder_x1',
    name: "Sidewinder X1",
    brand: "Artillery",
    power: 220,
    value: 2500,
    usefulLife: 2500,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // dimensões reais (mm)
    buildVolumeMm: { x: 300, y: 300, z: 400 },
    nozzleDiameterMm: 0.4,
    maxSpeedMmS: 150,
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'artillery_sidewinder_x2',
    name: "Sidewinder X2",
    brand: "Artillery",
    power: 260,
    value: 3000,
    usefulLife: 2800,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 330.2, y: 330.2, z: 330.2 },
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'artillery_sidewinder_x4',
    name: "Sidewinder X4",
    brand: "Artillery",
    power: 300,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'artillery_hornet',
    name: "Hornet",
    brand: "Artillery",
    power: 160,
    value: 1200,
    usefulLife: 2000,
    maintenancePerHour: 0.12,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'artillery_genius',
    name: "Genius",
    brand: "Artillery",
    power: 180,
    value: 1800,
    usefulLife: 2200,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'artillery_sw_x4_plus',
    name: "SW X4 Plus",
    brand: "Artillery",
    power: 350,
    value: 4500,
    usefulLife: 3500,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://artillery3d.com",
  },
  {
    id: 'qidi_x_plus',
    name: "X-Plus",
    brand: "Qidi Tech",
    power: 280,
    value: 4500,
    usefulLife: 3500,
    maintenancePerHour: 0.28,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://qidi3d.com",
  },
  {
    id: 'qidi_x_max',
    name: "X-Max",
    brand: "Qidi Tech",
    power: 350,
    value: 6000,
    usefulLife: 4000,
    maintenancePerHour: 0.35,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 321.6, y: 321.6, z: 321.6 },
    websiteUrl: "https://qidi3d.com",
  },
  {
    id: 'qidi_x_smart',
    name: "X-Smart",
    brand: "Qidi Tech",
    power: 200,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 175, y: 175, z: 175 },
    websiteUrl: "https://qidi3d.com",
  },
  {
    id: 'qidi_i_fast',
    name: "I-Fast",
    brand: "Qidi Tech",
    power: 350,
    value: 5500,
    usefulLife: 4000,
    maintenancePerHour: 0.32,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://qidi3d.com",
  },
  {
    id: 'qidi_i3',
    name: "Qidi I-3",
    brand: "Qidi Tech",
    power: 250,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://qidi3d.com",
  },
  {
    id: 'sovol_sv06',
    name: "SV06",
    brand: "Sovol",
    power: 160,
    value: 1400,
    usefulLife: 2000,
    maintenancePerHour: 0.12,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 229.6, y: 229.6, z: 229.6 },
    websiteUrl: "https://www.sovol3d.com",
  },
  {
    id: 'sovol_sv06_plus',
    name: "SV06 Plus",
    brand: "Sovol",
    power: 220,
    value: 2000,
    usefulLife: 2500,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 312.8, y: 312.8, z: 312.8 },
    websiteUrl: "https://www.sovol3d.com",
  },
  {
    id: 'sovol_sv07',
    name: "SV07",
    brand: "Sovol",
    power: 380,
    value: 2500,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // dimensões reais (mm)
    buildVolumeMm: { x: 220, y: 220, z: 250 },
    websiteUrl: "https://www.sovol3d.com",
  },
  {
    id: 'sovol_sv07_plus',
    name: "SV07 Plus",
    brand: "Sovol",
    power: 450,
    value: 3500,
    usefulLife: 3500,
    maintenancePerHour: 0.28,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // dimensões reais (mm)
    buildVolumeMm: { x: 300, y: 300, z: 350 },
    websiteUrl: "https://www.sovol3d.com",
  },
  {
    id: 'sovol_sv01',
    name: "SV01",
    brand: "Sovol",
    power: 200,
    value: 1500,
    usefulLife: 2000,
    maintenancePerHour: 0.14,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.sovol3d.com",
  },
  {
    id: 'ankermake_m5',
    name: "M5",
    brand: "AnkerMake",
    power: 300,
    value: 3500,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.ankermake.com",
  },
  {
    id: 'ankermake_m5c',
    name: "M5C",
    brand: "AnkerMake",
    power: 300,
    value: 2800,
    usefulLife: 3000,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.ankermake.com",
  },
  {
    id: 'ankermake_v6',
    name: "V6",
    brand: "AnkerMake",
    power: 400,
    value: 6000,
    usefulLife: 4000,
    maintenancePerHour: 0.35,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.ankermake.com",
  },
  {
    id: 'raise3d_e2',
    name: "E2",
    brand: "Raise3D",
    power: 350,
    value: 18000,
    usefulLife: 5000,
    maintenancePerHour: 0.5,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://www.raise3d.com",
  },
  {
    id: 'raise3d_pro3',
    name: "Pro3",
    brand: "Raise3D",
    power: 500,
    value: 25000,
    usefulLife: 6000,
    maintenancePerHour: 0.65,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://www.raise3d.com",
  },
  {
    id: 'raise3d_pro3_plus',
    name: "Pro3 Plus",
    brand: "Raise3D",
    power: 600,
    value: 35000,
    usefulLife: 6000,
    maintenancePerHour: 0.8,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://www.raise3d.com",
  },
  {
    id: 'raise3d_rf1000',
    name: "RF1000",
    brand: "Raise3D",
    power: 300,
    value: 8000,
    usefulLife: 4000,
    maintenancePerHour: 0.35,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://www.raise3d.com",
  },
  {
    id: 'snapmaker_j1',
    name: "J1",
    brand: "Snapmaker",
    power: 250,
    value: 6000,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://snapmaker.com",
  },
  {
    id: 'snapmaker_artisan',
    name: "Artisan",
    brand: "Snapmaker",
    power: 350,
    value: 8000,
    usefulLife: 3500,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://snapmaker.com",
  },
  {
    id: 'snapmaker_a350t',
    name: "A350T",
    brand: "Snapmaker",
    power: 300,
    value: 5000,
    usefulLife: 3000,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // volume aproximado (∛cm³) — dimensões reais indisponíveis
    buildVolumeMm: { x: 333.1, y: 333.1, z: 333.1 },
    nozzleDiameterMm: 0.4,
    maxSpeedMmS: 100,
    websiteUrl: "https://snapmaker.com",
  },
  {
    id: 'voron_v0',
    name: "V0.2",
    brand: "Voron",
    power: 180,
    value: 4000,
    usefulLife: 3000,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://vorondesign.com",
  },
  {
    id: 'voron_trident',
    name: "Trident",
    brand: "Voron",
    power: 350,
    value: 7000,
    usefulLife: 4000,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://vorondesign.com",
  },
  {
    id: 'voron_24',
    name: "2.4",
    brand: "Voron",
    power: 400,
    value: 8000,
    usefulLife: 4000,
    maintenancePerHour: 0.35,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    websiteUrl: "https://vorondesign.com",
  },
  {
    id: 'voron_switchwire',
    name: "Switchwire",
    brand: "Voron",
    power: 250,
    value: 5000,
    usefulLife: 3000,
    maintenancePerHour: 0.22,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://vorondesign.com",
  },
  {
    id: 'peopoly_lantech',
    name: "LanTech",
    brand: "Peopoly",
    power: 120,
    value: 3500,
    usefulLife: 2500,
    maintenancePerHour: 0.2,
    image: "/images/printers/fallback-fdm.svg",
    websiteUrl: "https://peopoly.net",
  },
  {
    id: 'peopoly_forge',
    name: "Forge",
    brand: "Peopoly",
    power: 400,
    value: 12000,
    usefulLife: 4000,
    maintenancePerHour: 0.45,
    image: "/images/printers/fallback-resin.svg",
    websiteUrl: "https://peopoly.net",
  },
  {
    id: 'phrozen_sonic_mega_8k',
    name: "Sonic Mega 8K",
    brand: "Phrozen",
    power: 180,
    value: 5500,
    usefulLife: 3000,
    maintenancePerHour: 0.3,
    image: "/images/printers/fallback-fdm.svg",
    technology: "fdm",
    // dimensões reais (mm)
    buildVolumeMm: { x: 330.2, y: 185.8, z: 400 },
    websiteUrl: "https://phrozen3d.com",
  },
  {
    id: 'phrozen_sonic_4k',
    name: "Sonic 4K",
    brand: "Phrozen",
    power: 100,
    value: 2500,
    usefulLife: 2000,
    maintenancePerHour: 0.15,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 134.4, y: 75.6, z: 200 },
    websiteUrl: "https://phrozen3d.com",
  },
  {
    id: 'phrozen_sonic_mini_8k',
    name: "Sonic Mini 8K",
    brand: "Phrozen",
    power: 80,
    value: 3000,
    usefulLife: 2500,
    maintenancePerHour: 0.18,
    image: "/images/printers/fallback-resin.svg",
    technology: "resin",
    // dimensões reais (mm)
    buildVolumeMm: { x: 165, y: 71.3, z: 180 },
    websiteUrl: "https://phrozen3d.com",
  },
  {
    id: 'custom',
    name: "Personalizada",
    brand: "Outra",
    power: 250,
    value: 3000,
    usefulLife: 3000,
    maintenancePerHour: 0.25,
    image: "/images/printers/fallback-fdm.svg",
  },
]

export function getPrinter(id: string): PrinterProfile {
  return printers.find(p => p.id === id) ?? printers[0]
}
