import { describe, it, expect } from "vitest";
import { parseGcodeTotals } from "@/shared/lib/gcodeTotals";

describe("parseGcodeTotals (D-EA6b slicer profile passthrough)", () => {
  it("reports layer height and line width from the Prusa/Orca/Bambu config block", () => {
    const gcode = [
      "; generated by PrusaSlicer 2.9.0",
      "; layer_height = 0.16",
      "; line_width = 0.42",
      "G1 X0 Y0 Z0.16 E0.1",
    ].join("\n");

    const totals = parseGcodeTotals(gcode);

    expect(totals.layerHeightMm).toBe(0.16);
    expect(totals.lineWidthMm).toBe(0.42);
    // E totals keep working as before.
    expect(totals.extrudedMm).toBe(0.1);
  });

  it("reads Cura-style ;WIDTH: and ;HEIGHT:", () => {
    const gcode = [";HEIGHT:0.15", ";WIDTH:0.4", "G1 X0 Y0 Z0.15 E0.1"].join(
      "\n",
    );

    const totals = parseGcodeTotals(gcode);

    expect(totals.layerHeightMm).toBe(0.15);
    expect(totals.lineWidthMm).toBe(0.4);
  });

  it("keeps the first value when the comment repeats (per-layer ;HEIGHT:)", () => {
    const gcode = [
      ";HEIGHT:0.15",
      "G1 X0 Y0 Z0.15 E0.1",
      ";HEIGHT:0.15",
      ";HEIGHT:0.2",
    ].join("\n");

    const totals = parseGcodeTotals(gcode);

    expect(totals.layerHeightMm).toBe(0.15);
  });

  it("leaves the profile fields absent when the slicer reports nothing", () => {
    const totals = parseGcodeTotals("G1 X0 Y0 Z0.2 E0.1");

    expect(totals.layerHeightMm).toBeUndefined();
    expect(totals.lineWidthMm).toBeUndefined();
  });

  it("rejects non-physical values (zero / negative / garbage)", () => {
    const totals = parseGcodeTotals(
      "; layer_height = 0\n; line_width = -1\n; layer_height = abc\nG1 E1",
    );

    expect(totals.layerHeightMm).toBeUndefined();
    expect(totals.lineWidthMm).toBeUndefined();
  });
});
