import { describe, it, expect } from "vitest";

import { parseGcode } from "../gcodeParser";

describe("parseGcode (D-EA6 geometry + D-EA6b profile)", () => {
  describe("dimensions from move bounding box", () => {
    it("derives dimensions from G0/G1 moves when ;MINX: is absent (Prusa/Orca/Bambu)", () => {
      const gcode = [
        "; generated by PrusaSlicer 2.9.0",
        "G90",
        "G28 ; home",
        "G1 Z0.2 F300",
        "G1 X0 Y0 Z0.2 E0.1",
        "G1 X20 Y0 Z0.2 E0.2",
        "G1 X20 Y15 Z0.2 E0.3",
        "G1 X0 Y15 Z0.2 E0.4",
        "G1 X0 Y0 Z5 E0.5",
      ].join("\n");

      const info = parseGcode(gcode);

      // 20 x 15 x 4.8 (Z 0.2 → 5)
      expect(info.printSize).toEqual({ x: 20, y: 15, z: 4.8 });
      expect(info.bounds).not.toBeNull();
      expect(info.bounds?.min).toEqual({ x: 0, y: 0, z: 0.2 });
      expect(info.bounds?.max).toEqual({ x: 20, y: 15, z: 5 });
    });

    it("keeps ;MINX: metadata authoritative over the accumulated bbox (Cura)", () => {
      const gcode = [
        "; generated by Cura_SteamEngine 5.7.0",
        ";MINX:0",
        ";MAXX:100",
        ";MINY:0",
        ";MAXY:50",
        ";MINZ:0",
        ";MAXZ:10",
        "G1 X10 Y10 Z0.2",
        "G1 X20 Y20 Z5",
      ].join("\n");

      const info = parseGcode(gcode);

      // Metadata (part extents per the slicer) wins over the move bbox
      // (10..20 x 10..20 x 0.2..5).
      expect(info.printSize).toEqual({ x: 100, y: 50, z: 10 });
    });

    it("byte-identical metadata result for a classic Cura header (no regression)", () => {
      const withMoves = [
        ";MINX:0",
        ";MAXX:100",
        ";MINY:0",
        ";MAXY:50",
        ";MINZ:0",
        ";MAXZ:10",
        "G1 X0 Y0 Z0.2",
        "G1 X100 Y50 Z10",
      ].join("\n");

      const info = parseGcode(withMoves);

      expect(info.printSize).toEqual({ x: 100, y: 50, z: 10 });
    });

    it("falls back to the bbox when ;MINX: exists but the pair is incomplete", () => {
      const gcode = [";MINX:0", "G1 X0 Y0 Z0.2", "G1 X30 Y20 Z1"].join("\n");

      const info = parseGcode(gcode);

      // No ;MAXX: → metadata cannot express X, the bbox fills it in.
      expect(info.printSize).toEqual({ x: 30, y: 20, z: 0.8 });
    });

    it("reports bounds null and zero dims when no positioned move exists", () => {
      const gcode = [
        ";TIME:3600",
        "M104 S200",
        "M140 S60",
        ";Filament used: 100mm",
      ].join("\n");

      const info = parseGcode(gcode);

      expect(info.printSize).toEqual({ x: 0, y: 0, z: 0 });
      expect(info.bounds).toBeNull();
    });

    it("keeps negative / off-bed coordinates in the derived dimensions", () => {
      const gcode = ["G1 X-10 Y-5 Z0.2", "G1 X10 Y5 Z0.2"].join("\n");

      const info = parseGcode(gcode);

      expect(info.printSize).toEqual({ x: 20, y: 10, z: 0 });
    });

    it("does not inflate dimensions with retractions", () => {
      const gcode = [
        "G1 X0 Y0 Z0.2 E1",
        "G1 X30 Y20 Z0.2 E2",
        "G1 E0 ; retract",
        "G1 E1.5 ; de-retract",
      ].join("\n");

      const info = parseGcode(gcode);

      expect(info.printSize).toEqual({ x: 30, y: 20, z: 0 });
    });
  });

  describe("D-EA6b slicer profile comments", () => {
    it("reads layer height from ; layer_height", () => {
      const info = parseGcode("; layer_height = 0.16\nG1 X0 Y0 Z0.16 E0.1");

      expect(info.layerHeight).toBe(0.16);
    });

    it("reads line width from ; line_width", () => {
      const info = parseGcode("; line_width = 0.42\nG1 X0 Y0 Z0.2 E0.1");

      expect(info.lineWidthMm).toBe(0.42);
    });

    it("reads Cura-style ;WIDTH: and ;HEIGHT: as fallbacks", () => {
      const info = parseGcode(";HEIGHT:0.15\n;WIDTH:0.4\nG1 X0 Y0 Z0.15 E0.1");

      expect(info.layerHeight).toBe(0.15);
      expect(info.lineWidthMm).toBe(0.4);
    });

    it("keeps ; layer_height over a later ;HEIGHT: line", () => {
      const info = parseGcode(
        "; layer_height = 0.16\n;HEIGHT:0.3\nG1 X0 Y0 Z0.16 E0.1",
      );

      expect(info.layerHeight).toBe(0.16);
    });

    it("leaves the profile fields unset when the slicer reports nothing", () => {
      const info = parseGcode("G1 X0 Y0 Z0.2 E0.1");

      expect(info.layerHeight).toBe(0);
      expect(info.lineWidthMm).toBeUndefined();
    });
  });
});
