import { describe, it, expect } from "vitest";
import { parseGcode } from "../gcodeParser";

describe("gcodeParser", () => {
  describe("TIME header parsing", () => {
    it("extracts print time from ;TIME: header (seconds)", () => {
      const result = parseGcode(";TIME:7200\nG1 X0 Y0 E0.1");
      expect(result.printTimeMinutes).toBe(120);
    });

    it("extracts print time of 90 minutes", () => {
      const result = parseGcode(";TIME:5400");
      expect(result.printTimeMinutes).toBe(90);
    });

    it("extracts print time of 60 minutes", () => {
      const result = parseGcode(";TIME:3600");
      expect(result.printTimeMinutes).toBe(60);
    });
  });

  describe("Filament used parsing", () => {
    it("extracts filament used in meters (e.g., 2.34m)", () => {
      const result = parseGcode(";Filament used: 2.34m");
      expect(result.filamentUsedMm).toBe(2340);
    });

    it("extracts filament used in mm (no unit suffix)", () => {
      const result = parseGcode(";Filament used: 500");
      expect(result.filamentUsedMm).toBe(500);
    });

    it("uses max E movement value as fallback when no filament header", () => {
      const gcode = [
        "G1 X0 Y0 E0",
        "G1 X10 Y10 E5.5",
        "G1 X20 Y20 E12.3",
        "G1 X30 Y30 E8.1",
      ].join("\n");
      const result = parseGcode(gcode);
      expect(result.filamentUsedMm).toBeCloseTo(12.3, 1);
    });
  });

  describe("Slicer identification", () => {
    it("extracts slicer from ; generated by comment", () => {
      const result = parseGcode("; generated by PrusaSlicer 2.6.0");
      expect(result.slicer).toBe("PrusaSlicer 2.6.0");
    });

    it("extracts slicer from ;Slicer: header", () => {
      const result = parseGcode(";Slicer:OrcaSlicer 2.0.0");
      expect(result.slicer).toBe("OrcaSlicer 2.0.0");
    });
  });

  describe("Filament type parsing", () => {
    it("extracts filament type from ;Filament type: header", () => {
      const result = parseGcode(";Filament type: PLA");
      expect(result.filamentType).toBe("PLA");
    });

    it("extracts filament type from ;Material: header", () => {
      const result = parseGcode(";Material: PETG");
      expect(result.filamentType).toBe("PETG");
    });
  });

  describe("Layer height parsing", () => {
    it("extracts layer height from ; layer_height = format", () => {
      const result = parseGcode("; layer_height = 0.2");
      expect(result.layerHeight).toBe(0.2);
    });

    it("extracts layer height from initial_layer_line_height when no layer_height", () => {
      const result = parseGcode("; initial_layer_line_height = 0.3");
      expect(result.layerHeight).toBe(0.3);
    });

    it("prefers layer_height over initial_layer_line_height", () => {
      const gcode = "; layer_height = 0.15\n; initial_layer_line_height = 0.3";
      const result = parseGcode(gcode);
      expect(result.layerHeight).toBe(0.15);
    });
  });

  describe("Temperature parsing", () => {
    it("extracts nozzle temp from ; nozzle_temperature = format", () => {
      const result = parseGcode("; nozzle_temperature = 250");
      expect(result.nozzleTemp).toBe(250);
    });

    it("extracts bed temp from ; bed_temperature = format", () => {
      const result = parseGcode("; bed_temperature = 80");
      expect(result.bedTemp).toBe(80);
    });

    it("extracts nozzle temp from M104 command", () => {
      const result = parseGcode("M104 S210");
      expect(result.nozzleTemp).toBe(210);
    });

    it("extracts bed temp from M140 command", () => {
      const result = parseGcode("M140 S60");
      expect(result.bedTemp).toBe(60);
    });

    it("extracts nozzle temp from M109 command", () => {
      const result = parseGcode("M109 S215");
      expect(result.nozzleTemp).toBe(215);
    });

    it("extracts bed temp from M190 command", () => {
      const result = parseGcode("M190 S65");
      expect(result.bedTemp).toBe(65);
    });
  });

  describe("Print size parsing", () => {
    it("extracts print bounding box from MIN/MAX headers", () => {
      const gcode = [
        ";MINX:10.5",
        ";MAXX:110.5",
        ";MINY:15.2",
        ";MAXY:95.2",
        ";MINZ:0.0",
        ";MAXZ:50.0",
      ].join("\n");
      const result = parseGcode(gcode);
      expect(result.printSize.x).toBeCloseTo(100, 0);
      expect(result.printSize.y).toBeCloseTo(80, 0);
      expect(result.printSize.z).toBeCloseTo(50, 0);
    });
  });

  describe("Filament weight estimation", () => {
    it("calculates filament weight from length", () => {
      // 1000mm of 1.75mm PLA filament
      const result = parseGcode(";Filament used: 1000\n");
      // Volume = π * (1.75/2/10)² * (1000/10) cm³ ≈ 2.405 cm³
      // Weight = 2.405 * 1.24 ≈ 2.98g
      expect(result.filamentUsedGrams).toBeGreaterThan(0);
      expect(result.filamentUsedGrams).toBeLessThan(5);
    });

    it("returns 0 grams when no filament used", () => {
      const result = parseGcode("");
      expect(result.filamentUsedGrams).toBe(0);
    });
  });

  describe("Combined realistic G-code", () => {
    it("parses a complete Orca Slicer G-code example", () => {
      const gcode = [
        "; generated by OrcaSlicer 2.0.0",
        ";Slicer:OrcaSlicer 2.0.0",
        ";TIME:3600",
        ";Filament used: 1.56m",
        ";Filament type: PETG",
        "; layer_height = 0.2",
        "; nozzle_temperature = 250",
        "; bed_temperature = 80",
        ";MINX:0",
        ";MAXX:100",
        ";MINY:0",
        ";MAXY:100",
      ].join("\n");
      const result = parseGcode(gcode);
      expect(result.printTimeMinutes).toBe(60);
      expect(result.filamentUsedMm).toBe(1560);
      expect(result.filamentType).toBe("PETG");
      expect(result.slicer).toBe("OrcaSlicer 2.0.0");
      expect(result.layerHeight).toBe(0.2);
      expect(result.nozzleTemp).toBe(250);
      expect(result.bedTemp).toBe(80);
      expect(result.printSize.x).toBeCloseTo(100, 0);
      expect(result.printSize.y).toBeCloseTo(100, 0);
    });

    it("parses a complete PrusaSlicer G-code example", () => {
      const gcode = [
        "; generated by PrusaSlicer 2.6.0",
        ";TIME:9000",
        ";Filament used: 4.5m",
        ";Filament type: PLA",
        "; layer_height = 0.15",
        "; nozzle_temperature = 215",
        "; bed_temperature = 60",
      ].join("\n");
      const result = parseGcode(gcode);
      expect(result.printTimeMinutes).toBe(150);
      expect(result.filamentUsedMm).toBe(4500);
      expect(result.filamentType).toBe("PLA");
      expect(result.slicer).toBe("PrusaSlicer 2.6.0");
      expect(result.layerHeight).toBe(0.15);
      expect(result.nozzleTemp).toBe(215);
      expect(result.bedTemp).toBe(60);
    });

    it("parses a complete Bambu Studio G-code example", () => {
      const gcode = [
        "; generated by BambuStudio_1.8.0",
        ";TIME:5400",
        ";Filament used: 3.8m",
        ";Filament type: PLA",
        "; layer_height = 0.2",
        ";MINX:10.5",
        ";MAXX:110.5",
        ";MINY:15.2",
        ";MAXY:95.2",
        ";MINZ:0.0",
        ";MAXZ:50.0",
      ].join("\n");
      const result = parseGcode(gcode);
      expect(result.printTimeMinutes).toBe(90);
      expect(result.filamentUsedMm).toBeCloseTo(3800, -1);
      expect(result.slicer).toBe("BambuStudio_1.8.0");
      expect(result.printSize.x).toBeCloseTo(100, 0);
      expect(result.printSize.y).toBeCloseTo(80, 0);
      expect(result.printSize.z).toBeCloseTo(50, 0);
    });
  });

  describe("PrusaSlicer/OrcaSlicer estimated printing time parsing", () => {
    it('parses "1h 23m" => 83 minutes (PrusaSlicer normal mode)', () => {
      const result = parseGcode(
        "; estimated printing time (normal mode) = 1h 23m",
      );
      expect(result.printTimeMinutes).toBe(83);
    });

    it('parses "45m 30s" => 46 minutes rounded', () => {
      const result = parseGcode(
        "; estimated printing time (normal mode) = 45m 30s",
      );
      expect(result.printTimeMinutes).toBe(46);
    });

    it('parses "2d 5h" => 3180 minutes', () => {
      const result = parseGcode(
        "; estimated printing time (normal mode) = 2d 5h",
      );
      expect(result.printTimeMinutes).toBe(3180);
    });

    it('parses "1h 23m 45s" => 84 minutes', () => {
      const result = parseGcode(
        "; estimated printing time (normal mode) = 1h 23m 45s",
      );
      expect(result.printTimeMinutes).toBe(84);
    });

    it('parses "2d 5h 10m 30s" => 3191 minutes', () => {
      const result = parseGcode(
        "; estimated printing time (normal mode) = 2d 5h 10m 30s",
      );
      expect(result.printTimeMinutes).toBe(3191);
    });

    it("parses estimated time without mode suffix", () => {
      const result = parseGcode("; estimated printing time = 2h 15m");
      expect(result.printTimeMinutes).toBe(135);
    });

    it("does not error when gcode has E moves but no TIME header (fallback 0)", () => {
      const result = parseGcode("G1 X0 Y0 E0.5\nG1 X10 Y10 E1.5");
      expect(result.printTimeMinutes).toBe(0);
      expect(result.filamentUsedMm).toBe(1.5);
    });
  });

  describe("Edge cases", () => {
    it("handles empty G-code gracefully", () => {
      const result = parseGcode("");
      expect(result.printTimeMinutes).toBe(0);
      expect(result.filamentUsedMm).toBe(0);
      expect(result.filamentUsedGrams).toBe(0);
    });

    it("handles malformed G-code gracefully", () => {
      const result = parseGcode("not a valid gcode\n;BROKEN: \nG1 : weird");
      expect(result.printTimeMinutes).toBe(0);
      expect(result.filamentUsedMm).toBe(0);
    });

    it("handles G-code with only comments", () => {
      const result = parseGcode("; just a comment\n; another comment");
      expect(result.printTimeMinutes).toBe(0);
      expect(result.filamentUsedMm).toBe(0);
    });

    it("handles G-code with only E movements and no headers", () => {
      const result = parseGcode("G1 X0 Y0 E0.5\nG1 X10 Y10 E1.5");
      // Uses max E (1.5) as filament length
      expect(result.filamentUsedMm).toBe(1.5);
    });

    it("handles comment-style temperature override with G-code commands", () => {
      const gcode = [
        "; nozzle_temperature = 240",
        "; bed_temperature = 70",
        "M104 S220", // G-code command overrides comment
      ].join("\n");
      const result = parseGcode(gcode);
      // Comment-parsed values come first, not overridden by G-code
      expect(result.nozzleTemp).toBe(240);
      expect(result.bedTemp).toBe(70);
    });
  });
});
