import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core'

// ── Fully Normalized Tables ────────────────────────────────────────────────

/**
 * Customers table.
 * IDs follow the pattern `cust_<timestamp>_<random>` as generated by
 * the existing Zustand store (customerStore.ts).
 */
export const customers = sqliteTable(
  'customers',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    company: text('company'),
    email: text('email'),
    phone: text('phone'),
    address: text('address'),
    notes: text('notes'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
)

/**
 * Quotes table.
 * customerSnapshot is stored as a JSON text blob (name, company, email, phone)
 * so that the quote remains self-contained even if the customer is later deleted.
 */
export const quotes = sqliteTable(
  'quotes',
  {
    id: text('id').primaryKey(),
    number: integer('number').notNull().unique(),
    title: text('title').notNull(),
    customerId: text('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    customerSnapshot: text('customer_snapshot'), // JSON
    globalDiscountPercent: real('global_discount_percent').default(0),
    subtotal: real('subtotal').default(0),
    discountAmount: real('discount_amount').default(0),
    total: real('total').default(0),
    status: text('status', { enum: ['draft', 'sent', 'approved', 'rejected'] })
      .default('draft'),
    validUntil: text('valid_until').notNull(),
    paymentTerms: text('payment_terms').default(''),
    deliveryEstimate: text('delivery_estimate').default(''),
    footerNote: text('footer_note'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
    exportedAt: integer('exported_at'),
  },
)

/**
 * Quote items (line items).
 * Each item links back to a history entry (for cost data) and to a quote.
 */
export const quoteItems = sqliteTable(
  'quote_items',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    quoteId: text('quote_id').notNull().references(() => quotes.id, { onDelete: 'cascade' }),
    historyEntryId: text('history_entry_id').notNull(),
    name: text('name').notNull(),
    quantity: integer('quantity').default(1),
    unitPrice: real('unit_price').default(0),
    totalPrice: real('total_price').default(0),
    discountPercent: real('discount_percent').default(0),
  },
)

/**
 * History entries — saved calculation results.
 * resultJson holds the full CalculationResult object.
 * snapshotJson holds the CalculationSnapshot (all calculator inputs).
 */
export const historyEntries = sqliteTable(
  'history_entries',
  {
    id: text('id').primaryKey(),
    timestamp: integer('timestamp').notNull(),
    type: text('type', { enum: ['fdm', 'resin'] }).notNull(),
    name: text('name').notNull(),
    summary: text('summary').default(''),
    totalCost: real('total_cost').default(0),
    sellPrice: real('sell_price').default(0),
    profit: real('profit').default(0),
    resultJson: text('result_json').notNull(), // JSON: CalculationResult
    snapshotJson: text('snapshot_json'),       // JSON: CalculationSnapshot | null
  },
)

/**
 * Filament spools — inventory tracking.
 */
export const filamentSpools = sqliteTable(
  'filament_spools',
  {
    id: text('id').primaryKey(),
    brand: text('brand').default(''),
    material: text('material').default('PLA'),
    color: text('color').default(''),
    colorHex: text('color_hex').default(''),
    weightGrams: real('weight_grams').default(0),
    originalWeightGrams: real('original_weight_grams').default(1000),
    costPerKg: real('cost_per_kg').default(0),
    diameterMm: real('diameter_mm').default(1.75),
    dateAdded: integer('date_added').notNull(),
    notes: text('notes').default(''),
    status: text('status', { enum: ['in_stock', 'on_the_way', 'empty'] })
      .default('in_stock'),
    purchaseStore: text('purchase_store').default(''),
  },
)

/**
 * Built-in printer catalog.
 * Seeded from printers-database.json / printers.ts.
 */
export const catalogPrinters = sqliteTable(
  'catalog_printers',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    brand: text('brand').notNull(),
    power: real('power').notNull(),
    value: real('value').notNull(),
    usefulLife: integer('useful_life').notNull(),
    maintenancePerHour: real('maintenance_per_hour').notNull(),
    image: text('image'),
    maxFilaments: integer('max_filaments'),
    custom: integer('custom').default(0),
  },
)

/**
 * Built-in material catalog.
 */
export const catalogMaterials = sqliteTable(
  'catalog_materials',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    density: real('density').notNull(),
    avgPrice: real('avg_price').notNull(),
    type: text('type', { enum: ['fdm', 'resin'] }).notNull(),
    custom: integer('custom').default(0),
  },
)

/**
 * Built-in marketplace catalog.
 */
export const catalogMarketplaces = sqliteTable(
  'catalog_marketplaces',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    feePercent: real('fee_percent').notNull(),
    feeFixed: real('fee_fixed').notNull(),
    hasFreeShipping: integer('has_free_shipping').default(0),
    shippingFeePercent: real('shipping_fee_percent'),
    custom: integer('custom').default(0),
  },
)

/**
 * Products — standalone sale inventory (Issue #68).
 * IDs follow the pattern `prod_<timestamp>_<random>` as generated by
 * the Zustand store (productInventory.ts). No foreign keys: products are
 * self-contained (sold flag is toggled manually, never derived).
 */
export const products = sqliteTable(
  'products',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    weightGrams: real('weight_grams').default(0),
    filamentType: text('filament_type').default(''),
    costPrice: real('cost_price').default(0),
    salePrice: real('sale_price').default(0),
    sold: integer('sold').default(0),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
)

// ── JSON Blob / Key-Value Tables ──────────────────────────────────────────
/**
 * Single-row table for the entire calculator state.
 * The CHECK(id = 1) constraint ensures only one row exists.
 */
export const calculatorState = sqliteTable(
  'calculator_state',
  {
    id: integer('id').primaryKey().default(1),
    stateJson: text('state_json').notNull(),  // JSON: CalculatorState
    updatedAt: integer('updated_at').notNull(),
  },
)

/**
 * Key-value store for app settings:
 *   - consent (GDPR / cookie consent)
 *   - tutorial (completed flag)
 *   - dashboard prefs
 *   - onboarding flag
 *   - currency setting
 */
export const appSettings = sqliteTable(
  'app_settings',
  {
    key: text('key').primaryKey(),
    value: text('value').notNull(),
  },
)

/**
 * Generic key-value storage for IPC persistence layer.
 * Used by the StoragePort adapter to replace localStorage.
 * Maps 1:1 with the existing localStorage keys:
 *   open3dcalc_settings_v2, open3dcalc_history_v2,
 *   open3dcalc_quotes_v1, open3dcalc_customers_v1, etc.
 */
export const storage = sqliteTable(
  'storage',
  {
    key: text('key').primaryKey(),
    value: text('value').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
)

// ── Inferred Types ─────────────────────────────────────────────────────────

export type Customer = typeof customers.$inferSelect
export type NewCustomer = typeof customers.$inferInsert

export type Quote = typeof quotes.$inferSelect
export type NewQuote = typeof quotes.$inferInsert

export type QuoteItem = typeof quoteItems.$inferSelect
export type NewQuoteItem = typeof quoteItems.$inferInsert

export type HistoryEntry = typeof historyEntries.$inferSelect
export type NewHistoryEntry = typeof historyEntries.$inferInsert

export type FilamentSpool = typeof filamentSpools.$inferSelect
export type NewFilamentSpool = typeof filamentSpools.$inferInsert

export type Product = typeof products.$inferSelect
export type NewProduct = typeof products.$inferInsert

export type CatalogPrinter = typeof catalogPrinters.$inferSelect
export type NewCatalogPrinter = typeof catalogPrinters.$inferInsert

export type CatalogMaterial = typeof catalogMaterials.$inferSelect
export type NewCatalogMaterial = typeof catalogMaterials.$inferInsert

export type CatalogMarketplace = typeof catalogMarketplaces.$inferSelect
export type NewCatalogMarketplace = typeof catalogMarketplaces.$inferInsert

export type CalculatorState = typeof calculatorState.$inferSelect
export type NewCalculatorState = typeof calculatorState.$inferInsert

export type AppSetting = typeof appSettings.$inferSelect
export type NewAppSetting = typeof appSettings.$inferInsert

export type StorageRow = typeof storage.$inferSelect
export type NewStorageRow = typeof storage.$inferInsert
