/**
 * Vite plugin: compile `docs/wiki/<locale>/<slug>.md` into JS modules at build
 * time.
 *
 * ARCHITECTURE DECISION (council:2026-09-19:open3dcalc-wiki-docs) — the wiki is
 * AUTHORED IN MARKDOWN but NEVER parsed at runtime. This plugin is the only
 * place where the remark/rehype pipeline runs; `markdownToHtml()` produces the
 * finished HTML string here, and the client receives a plain data module. Zero
 * markdown parser in the bundle, zero runtime dependencies added, and the
 * sanitizing pipeline (rehype-sanitize) stays on the build side.
 *
 * Emit two module shapes:
 * - `docs/wiki/<locale>/<slug>.md`            -> { slug, locale, frontmatter, toc, html }
 * - `docs/wiki/<locale>/<slug>.md?wiki-meta`  -> { frontmatter } only
 *
 * The `?wiki-meta` variant exists so the article index can be eager-loaded
 * (`import.meta.glob(..., { eager: true, query: "?wiki-meta", import: "frontmatter" })`)
 * without pulling a single byte of article HTML into the main chunk. Article
 * bodies stay lazy via a plain `import.meta.glob(..., { eager: false })`, which
 * produces one dynamic import per locale.
 *
 * `slug` and `locale` are derived from the file path, so the module is the
 * single source of truth for its own identity. Reverting this to a runtime
 * markdown parser requires a new council (see docs/wiki/README.md).
 *
 * LAZY LOADING (R1) — validated, not assumed: the article bodies are loaded
 * with `import.meta.glob(..., { eager: false })`, which turns each locale into
 * one dynamic import. Dynamic import of a local chunk under Electron's
 * `file://` + `script-src 'self'` CSP was verified empirically (a probe build
 * with this plugin, run under Electron with the production CSP active: the
 * lazy wiki chunks loaded and the CSP blocked a control inline script), and
 * the shipped desktop bundle already relies on the same mechanism for five
 * other chunks (csvExport, GcodePreviewPanel, gcodeParser, stlParser,
 * rendererSweep). The `eager: true` fallback stays documented, not applied.
 *
 * Authoring contract (enforced by failing the build, never by silently
 * ignoring): frontmatter must be the flat schema accepted by
 * `markdownToHtml()` — `title` and `order` required, `tourId` optional.
 */
import type { Plugin } from "vite";

import { markdownToHtml } from "../../src/shared/lib/wiki/markdownToHtml";
import type {
  WikiFrontmatter,
  WikiTocItem,
} from "../../src/shared/lib/wiki/markdownToHtml";

/** Query that selects the metadata-only module. */
export const WIKI_META_QUERY = "wiki-meta";

/**
 * Matches the tail of an absolute id, on either separator, e.g.
 * `/home/u/open3dcalc/docs/wiki/pt-BR/calculadora.md` -> locale "pt-BR",
 * slug "calculadora". A nested slug keeps its subpath (`a/b/c`), and anything
 * not under `docs/wiki/<locale>/` (like `docs/conventions.md`) does not match.
 */
const WIKI_ARTICLE_PATTERN = /(?:^|\/)docs\/wiki\/([^/]+)\/(.+)\.md$/;

/** Shape of the full article module. */
export interface WikiArticleModule {
  slug: string;
  locale: string;
  frontmatter: WikiFrontmatter;
  toc: WikiTocItem[];
  html: string;
}

/** Derive the locale and slug of an article from its resolved id. */
function resolveArticleIdentity(id: string): {
  slug: string;
  locale: string;
} | null {
  const match = WIKI_ARTICLE_PATTERN.exec(id.replace(/\\/g, "/"));
  if (match === null) return null;
  return { locale: match[1], slug: match[2] };
}

/**
 * Compile a wiki markdown file into a JS module.
 *
 * @returns the module source, or `null` when the id is not a wiki article (the
 * file is left for other plugins / Vite's own handling).
 */
export function markdownWikiPlugin(): Plugin {
  return {
    name: "open3dcalc-markdown-wiki",
    transform(code, id) {
      const pathEnd = id.indexOf("?");
      const filePath = pathEnd === -1 ? id : id.slice(0, pathEnd);
      if (!filePath.endsWith(".md")) return null;

      const identity = resolveArticleIdentity(filePath);
      if (identity === null) return null;

      const query = pathEnd === -1 ? "" : id.slice(pathEnd + 1);
      const { frontmatter, toc, html } = markdownToHtml(code);

      const lines =
        query === WIKI_META_QUERY
          ? [
              "// Generated by markdownWikiPlugin: metadata only (no toc/html).",
              `export const frontmatter = ${JSON.stringify(frontmatter)};`,
            ]
          : [
              "// Generated by markdownWikiPlugin: compile-time markdown -> HTML.",
              `export const slug = ${JSON.stringify(identity.slug)};`,
              `export const locale = ${JSON.stringify(identity.locale)};`,
              `export const frontmatter = ${JSON.stringify(frontmatter)};`,
              `export const toc = ${JSON.stringify(toc)};`,
              `export const html = ${JSON.stringify(html)};`,
            ];

      return { code: lines.join("\n"), map: null };
    },
  };
}
