; generated by OrcaSlicer 2.3.0
; model printing time: 0h 30m 0s
; total estimated time: 0h 30m 0s
; filament used [mm] = 100
; filament used [cm3] = 0.24
; total filament used [g] = 0.3
; layer_height = 0.2
; line_width = 0.4

G90 ; absolute positioning
M83 ; relative extrusion
G28 ; home
G1 Z5 F6000 ; lift
G1 X0 Y0 Z0.2 F6000

;LAYER:0
;TYPE:inner wall
G1 X20 Y0 E5 F1200
G1 X20 Y20 E5
G1 X0 Y20 E5
G1 X0 Y0 E5

;LAYER:1
;TYPE:inner wall
G1 Z0.4 F6000
G1 X20 Y0 E5 F1200
G1 X20 Y20 E5
G1 X0 Y20 E5
G1 X0 Y0 E5

;LAYER:2
;TYPE:inner wall
G1 Z0.6 F6000
G1 X20 Y0 E5 F1200
G1 X20 Y20 E5
G1 X0 Y20 E5
G1 X0 Y0 E5

;LAYER:3
;TYPE:top surface
G1 Z0.8 F6000
G1 X20 Y0 E5 F1200
G1 X20 Y20 E5
G1 X0 Y20 E5
G1 X0 Y0 E5

;LAYER:4
;TYPE:top surface
G1 Z1.0 F6000
G1 X20 Y0 E5 F1200
G1 X20 Y20 E5
G1 X0 Y20 E5
G1 X0 Y0 E5

M84 ; disable motors
