/**
 * Compile-time markdown -> HTML converter for the in-app wiki.
 *
 * The full remark/rehype pipeline runs HERE, at build time (invoked from the
 * Vite plugin). The runtime receives the finished HTML string and renders it
 * with a single `dangerouslySetInnerHTML` per article. No markdown parser ever
 * ships to the client, and none of the remark/rehype packages are runtime
 * dependencies — they are devDependencies used only by this module and tests.
 *
 * Supported markdown subset (documented in docs/wiki/README.md):
 * - ATX headings h1-h3, with stable ids generated by rehype-slug
 * - ordered and unordered lists
 * - fenced code blocks
 * - links, bold, inline code
 * - flat YAML frontmatter: `title` (required), `order` (required), `tourId`
 *
 * Sanitizing is defense in depth: the content is first-party, but raw HTML is
 * dropped by remark-rehype and rehype-sanitize strips anything dangerous, so
 * neither `<script>` nor event handlers can reach the rendered article.
 */

import type { Root as HastRoot, Element } from "hast";
import type { Root as MdastRoot, Yaml } from "mdast";
import remarkFrontmatter from "remark-frontmatter";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeSanitize from "rehype-sanitize";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import { unified } from "unified";
import type { Transformer } from "unified";

/** Frontmatter of a wiki article. Matches the docs/wiki/README.md schema. */
export interface WikiFrontmatter {
  /** Human-readable article title (also used as the nav/TOC root label). */
  title: string;
  /** Sorting position of the article inside its locale. Lower comes first. */
  order: number;
  /** Optional tutorial tour this article is the entry point for. */
  tourId?: string;
}

/** One entry of the build-time table of contents, derived from the headings. */
export interface WikiTocItem {
  /** Heading level: 1, 2 or 3. */
  depth: 1 | 2 | 3;
  /** Visible heading text, with all markup flattened. */
  text: string;
  /** Anchor id written by rehype-slug onto the heading element. */
  slug: string;
}

/** Result of converting one markdown article. */
export interface MarkdownToHtmlResult {
  frontmatter: WikiFrontmatter;
  toc: WikiTocItem[];
  html: string;
}

const HEADING_DEPTH_BY_TAG: ReadonlyMap<string, 1 | 2 | 3> = new Map([
  ["h1", 1],
  ["h2", 2],
  ["h3", 3],
]);

const KNOWN_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  "title",
  "order",
  "tourId",
]);

/** Only bare decimals are read as numbers: keeps `1_000` and `Infinity` out. */
const NUMERIC_PATTERN = /^-?\d+(?:\.\d+)?$/;

/** Frontmatter keys are restricted to a simple, documented identifier shape. */
const FRONTMATTER_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_-]*$/;

type FrontmatterValue = string | number;

function parseScalarValue(rawValue: string, line: number): FrontmatterValue {
  const value = rawValue.trim();
  if (value.startsWith('"') && value.endsWith('"') && value.length > 1) {
    return value.slice(1, -1).replace(/\\(.)/g, "$1");
  }
  if (value.startsWith("'") && value.endsWith("'") && value.length > 1) {
    return value.slice(1, -1).replace(/\\'/g, "'");
  }
  if (NUMERIC_PATTERN.test(value)) {
    return Number(value);
  }
  if (value === "") {
    throw new Error(
      `wiki frontmatter: line ${line} has an empty value; set a title/order/tourId value or drop the line`,
    );
  }
  return value;
}

/**
 * Parse the flat YAML subset accepted in wiki frontmatter.
 *
 * This is deliberately NOT a general YAML parser: the schema is exactly
 * `title`, `order` and optional `tourId`, all flat scalars. Anything outside
 * that subset fails the build with a message pointing at the offending line,
 * which is how the documented authoring contract stays enforced.
 */
function parseFrontmatter(raw: string): WikiFrontmatter {
  const parsed: Record<string, FrontmatterValue> = {};

  raw.split(/\r?\n/).forEach((line, index) => {
    const lineNumber = index + 1;
    const content = line.trim();
    if (content === "") return;

    const colon = content.indexOf(":");
    if (colon === -1) {
      throw new Error(
        `wiki frontmatter: line ${lineNumber} is not a "key: value" pair: ${JSON.stringify(content)}`,
      );
    }

    const key = content.slice(0, colon).trim();
    if (!FRONTMATTER_KEY_PATTERN.test(key)) {
      throw new Error(
        `wiki frontmatter: line ${lineNumber} has an invalid key: ${JSON.stringify(key)}`,
      );
    }
    if (!KNOWN_FRONTMATTER_KEYS.has(key)) {
      throw new Error(
        `wiki frontmatter: line ${lineNumber} uses unknown key "${key}"; supported keys are title, order and tourId`,
      );
    }

    parsed[key] = parseScalarValue(content.slice(colon + 1), lineNumber);
  });

  const { title, order, tourId } = parsed;

  if (typeof title !== "string" || title.trim() === "") {
    throw new Error(
      "wiki frontmatter: 'title' is required and must be a non-empty string",
    );
  }
  if (typeof order !== "number" || !Number.isFinite(order)) {
    throw new Error(
      "wiki frontmatter: 'order' is required and must be a number (e.g. order: 3)",
    );
  }
  if (
    tourId !== undefined &&
    (typeof tourId !== "string" || tourId.trim() === "")
  ) {
    throw new Error(
      "wiki frontmatter: 'tourId' must be a non-empty string when present, or omitted",
    );
  }

  const frontmatter: WikiFrontmatter = { title, order };
  if (typeof tourId === "string") {
    frontmatter.tourId = tourId;
  }
  return frontmatter;
}

/** Flatten an element's descendants into visible text. */
function elementText(node: Element): string {
  let text = "";
  for (const child of node.children) {
    if (child.type === "text") {
      text += child.value;
    } else if (child.type === "element") {
      text += elementText(child);
    }
  }
  return text;
}

/** Collect h1-h3 (text + slug) in document order. Runs after rehype-slug. */
function collectToc(node: HastRoot | Element, toc: WikiTocItem[]): void {
  for (const child of node.children) {
    if (child.type !== "element") continue;

    const depth = HEADING_DEPTH_BY_TAG.get(child.tagName);
    if (depth !== undefined) {
      const id = child.properties?.id;
      if (typeof id === "string") {
        const text = elementText(child).trim();
        if (text !== "") {
          toc.push({ depth, text, slug: id });
        }
      }
    }
    collectToc(child, toc);
  }
}

/**
 * Convert one wiki markdown article into frontmatter, table of contents and
 * HTML. Pure: no I/O and no side effects — identical input always yields
 * identical output.
 *
 * @throws when the frontmatter is missing, malformed or does not match the
 * documented schema. The build fails loudly rather than shipping an article
 * with an unknown shape.
 */
export function markdownToHtml(md: string): MarkdownToHtmlResult {
  let frontmatter: WikiFrontmatter | undefined;
  const toc: WikiTocItem[] = [];

  const captureFrontmatter = (): Transformer<MdastRoot> => (tree) => {
    const yamlNode = tree.children.find(
      (node): node is Yaml => node.type === "yaml",
    );
    frontmatter = yamlNode ? parseFrontmatter(yamlNode.value) : undefined;
  };

  const extractToc = (): Transformer<HastRoot> => (tree) => {
    collectToc(tree, toc);
  };

  const file = unified()
    .use(remarkParse)
    .use(remarkFrontmatter, ["yaml"])
    .use(captureFrontmatter)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeSanitize)
    .use(extractToc)
    .use(rehypeStringify)
    .processSync(md);

  if (frontmatter === undefined) {
    throw new Error(
      "wiki markdown: article is missing YAML frontmatter (title and order are required)",
    );
  }

  return { frontmatter, toc, html: String(file) };
}
