; generated by PrusaSlicer 2.9.0+win64 on 2026-09-18 at 12:00:00 UTC
; total filament used [g] = 9.98
; filament used [mm] = 13.3
; filament used [cm3] = 8.05
; estimated printing time (normal mode) = 0h 12m 30s
; layer_height = 0.2
; line_width = 0.4
; bed_shape = 0x0,250x0,250x210,0x210
; max_print_height = 210

M82 ; absolute extrusion
G28 ; home
G90 ; absolute positioning
G1 Z5 F6000 ; lift

;LAYER:0
;TYPE:skirt
G1 X0 Y0 Z0.2 F6000
G1 X20 Y0 E2.6607 F1200
G1 X20 Y20 E5.3214
G1 X0 Y20 E7.9821
G1 X0 Y0 E10.6428

;LAYER:1
;TYPE:perimeter
G1 Z0.4 F6000
G1 X20 Y0 E13.3035 F1200
G1 X20 Y20 E15.9642
G1 X0 Y20 E18.6249
G1 X0 Y0 E21.2856

;LAYER:2
;TYPE:perimeter
G1 Z0.6 F6000
G1 X20 Y0 E23.9463 F1200
G1 X20 Y20 E26.607
G1 X0 Y20 E29.2677
G1 X0 Y0 E31.9284

;LAYER:3
;TYPE:infill
G1 Z0.8 F6000
G1 X10 Y10 E33.5 F1200
G1 X10 Y20 E35.0
G1 X0 Y20 E36.5

;LAYER:4
;TYPE:top solid infill
G1 Z1.0 F6000
G1 X20 Y20 E38.0 F1200
G1 X0 Y20 E39.5
G1 X0 Y0 E41.0

M84 ; disable motors
